# Generated by Django 4.2.9 on 2026-03-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('consumption_kwh', models.FloatField()),
                ('demand_kw', models.FloatField()),
                ('voltage', models.FloatField(default=230.0)),
                ('current', models.FloatField(default=0.0)),
                ('power_factor', models.FloatField(default=0.95)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='meter', max_length=50)),
                ('location', models.CharField(default='Building A', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'energy_data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
