# Generated by Django 4.2.9 on 2026-03-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('strategy', models.CharField(choices=[('peak_shaving', 'Peak Shaving'), ('load_shifting', 'Load Shifting'), ('demand_response', 'Demand Response')], default='peak_shaving', max_length=50)),
                ('peak_demand_before', models.FloatField()),
                ('peak_demand_after', models.FloatField()),
                ('cost_before', models.FloatField()),
                ('cost_after', models.FloatField()),
                ('savings_kwh', models.FloatField()),
                ('savings_cost', models.FloatField()),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'optimization_results',
                'ordering': ['-date'],
            },
        ),
    ]
