# Generated by Django 4.2.9 on 2026-03-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_consumption', models.FloatField()),
                ('actual_consumption', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forecast_results',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('epochs', models.IntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'model_training_jobs',
                'ordering': ['-started_at'],
            },
        ),
    ]
