# Generated by Django 4.2.9 on 2026-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
